backend:
  name: git-gateway
  branch: master
  squash_merges: true
publish_mode: editorial_workflow
media_folder: images
collections:
  - name: "posts"
    label: "Posts"
    folder: "source/_posts/2018"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Image Filename", name: "image", widget: "string", required: false}
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "projects"
    label: "Projects"
    folder: "source/_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Project name", name: "title", widget: "string"}
      - {label: "Link to source code", name: "source", widget: "string", required: false}
      - {label: "Link to live demo", name: "demo", widget: "string", required: false}
      - {label: "Description", name: "body", widget: "text"}
